# =========================
# Banco de dados (PROD)
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / Hibernate (PROD)
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =========================
# JWT (PROD)
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=60

# =========================
# Erros (PROD)
# =========================
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-binding-errors=never
server.error.whitelabel.enabled=false

# =========================
# Cookies (PROD)
# =========================
app.auth.cookie-secure=true

# =========================
# Proxy/Cloud (Render)
# =========================
server.forward-headers-strategy=framework

# =========================
# Frontend URL
# =========================
app.frontend-url=${APP_FRONTEND_URL}

# =========================
# Health Check
# =========================
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
