# =========================
# Banco de dados (DEV)
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/beacon_navigator?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=seuusuario
spring.datasource.password=suasenha
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / Hibernate (DEV)
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =========================
# JWT (DEV)
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=${JWT_EXP_MINUTES:120}

# =========================
# Erros (DEV)
# =========================
server.error.include-message=always
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-binding-errors=always
server.error.whitelabel.enabled=false


