# =========================
# Banco de dados (DEV)
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/beacon_navigator?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=618312
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / Hibernate (DEV)
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =========================
# JWT (DEV)
# =========================
jwt.secret=beacon_navigator_jwt_secret_dev_mais_de_32_chars_1234567890
jwt.expiration-minutes=120

# =========================
# Erros (DEV)
# =========================
server.error.include-message=always
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-binding-errors=always
server.error.whitelabel.enabled=false

# =========================
# Google OAuth2 Login (DEV)
# =========================
spring.security.oauth2.client.registration.google.client-id=SEU_CLIENT_ID_DO_GOOGLE_AQUI
spring.security.oauth2.client.registration.google.client-secret=SEU_CLIENT_SECRET_DO_GOOGLE_AQUI
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email
